// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

async function forEach(iterator, f) {
  var iteratorDone = false;
  while(!iteratorDone) {
    var match = await iterator.next();
    Curry._1(f, match.value);
    iteratorDone = match.done;
  };
}

export {
  forEach ,
}
/* No side effect */
